package redhat.smartmetervent;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Role(org.kie.api.definition.type.Role.Type.EVENT)
@org.kie.api.definition.type.Timestamp("timestamp")
public class OutageEvent implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String meterID;
   private java.util.Date timestamp;
   private java.lang.String zone;

   public OutageEvent()
   {
   }

   public java.lang.String getMeterID()
   {
      return this.meterID;
   }

   public void setMeterID(java.lang.String meterID)
   {
      this.meterID = meterID;
   }

   public java.util.Date getTimestamp()
   {
      return this.timestamp;
   }

   public void setTimestamp(java.util.Date timestamp)
   {
      this.timestamp = timestamp;
   }

   public java.lang.String getZone()
   {
      return this.zone;
   }

   public void setZone(java.lang.String zone)
   {
      this.zone = zone;
   }

   public void setNofication(java.lang.String id, java.lang.String emailId, java.lang.String message)
   {

      if (this.notification == null)
      {
         this.notification = new redhat.smartmetervent.Notification();
      }

      this.notification.setId(id);
      this.notification.setEmailId(emailId);
      this.notification.setMessage(message);
   }

   public OutageEvent(java.lang.String meterID, java.util.Date timestamp,
         java.lang.String zone)
   {
      this.meterID = meterID;
      this.timestamp = timestamp;
      this.zone = zone;
   }

}